# 👻  **Taller 2 - Numpy: Indexing - Slicing**

<img src="https://www.udistrital.edu.co/themes/custom/versh/images/default/preloader.png" align="left" width="192px" height="192px"/>
<img align="left" width="0" height="192px" hspace="10"/>

> Juan Felipe Rodríguez Galindo  - **COD. 20181020158**
<br></br>
[![Juan Felipe Rodriguez Galindo](https://img.shields.io/badge/Juferoga-github-br?style=flat-square)](https://gitlab.com/Juferoga)
[![License](https://img.shields.io/badge/License-GPL_V.3-blue?style=flat-square)](https://www.gnu.org/licenses/gpl-3.0.html)


Introducción a la Ciencia de Datos

Desarrrollo del taller propuesto en la clase de introducción a la ciencia de datos.

## Taller

```
Generar un arreglo tridimensional de tamaño 9x9x9 con los número enteros del 0 al 728.

Imaginar que el arreglo se divide en 27 arreglos de 3x3x3; desarrollar una función que permita intercambiar la posición de dos de estos bloques, pasándole como argumento únicamente la identificación de los bloques a intercambiar (los bloques se deben identificar con números del 0 al 26)
```

## **Desarrollo**

 ## Importando numpy
 Librería de python que permite generar arreglos.

In [0]:
# Importamos el modulo Random
import numpy as np

# definición de variables

# creamos un array con los identificadores para poder manipularlos de una forma más simple
id = np.array([[0, 0, 0],[0, 0, 1],[0, 0, 2],[0, 1, 0],[0, 2, 2],[0, 2, 3],
               [0, 2, 0],[0, 2, 1],[0, 2, 2],[1, 0, 0],[1, 0, 1],[1, 0, 2],
               [1, 1, 0],[1, 1, 1],[1, 1, 2],[1, 2, 0],[1, 2, 1],[1, 2, 2],
               [2, 0, 0],[2, 0, 1],[2, 0, 2],[2, 1, 0],[2, 1, 1],[2, 1, 2],
               [2, 2, 0],[2, 2, 1],[2, 2, 2] ])

# Mostramos los identificadores para que el usuario pueda elejir el que desaea cambiar
print("identificadores de las matrices o de los cubos de Rubik \n",id)

identificadores de las matrices o de los cubos de Rubik 
 [[0 0 0]
 [0 0 1]
 [0 0 2]
 [0 1 0]
 [0 2 2]
 [0 2 3]
 [0 2 0]
 [0 2 1]
 [0 2 2]
 [1 0 0]
 [1 0 1]
 [1 0 2]
 [1 1 0]
 [1 1 1]
 [1 1 2]
 [1 2 0]
 [1 2 1]
 [1 2 2]
 [2 0 0]
 [2 0 1]
 [2 0 2]
 [2 1 0]
 [2 1 1]
 [2 1 2]
 [2 2 0]
 [2 2 1]
 [2 2 2]]


Creamos las funciones utiles para nuestro programa.

In [0]:
########## Funciones utiles ##########

# lim : lo uilizamos para delimitar tanto el eje x,y,z del cubo
def lim(fil, col, z):
    # x
    row = np.arange(fil*3, fil*3+3, 1)
    # y
    col = np.arange(col*3, col*3+3, 1)
    # la Z
    la_z = np.arange(z*3, z*3+3, 1)
    return row, col, la_z

# cb : creamos un nuevo arreglo, le damos un amejor manejo por medio de la funcion
# meshgrid (https://docs.scipy.org/doc/numpy/reference/generated/numpy.meshgrid.html)
def cb(m1, m2, m3):
    return np.array(np.meshgrid(m1, m2, m3)).T.reshape(-1, 3)


# replace : lo utilizamos para reemplazar los datos de posicion a posicion 
def replace(nums, id_replazo, z):
    for i, val in enumerate(nums):
        z[id_replazo[i][0], id_replazo[i]
            [1], id_replazo[i][2]] = val

# cp: Creamos una copia que mantiene los datos que se reemplazaran primero
def cp(id, z):
    copia = []
    for i in id:
        copia.append(z.item(*i))
    return copia

**Dando solucion a punto 1** creamos el arreglo de 729 elemntos y le damos la forma de 9x9x9.

In [0]:
# creamos el arreglo de 729 elementos y lo convertimos o realizamos un reshape
# para que cumpla con la condicion de se 9x9x9 (Solucion Punto 1)
elarreglo = np.arange(729).reshape(9, 9, 9)

Pedimos los datos al usuario.

In [0]:
# ingreso de datos de los respectivos identificadores que permitiran cambiar las
# posiciones de estos
num1 = int(input('Ingresa identificador 1: '))
num2 = int(input('Ingresa identificador 2: '))

Ingresa identificador 1: 1
Ingresa identificador 2: 15


Utilizamos los datos ingresados para ubicar los limites haciendo uso de los identificadores

In [0]:
# utilizamos los datos ingresados para ubicar un limite en las tres posiciones x,y,z con los identificadores
row, col, la_z = lim(*id[num1])
# convertimpos los ids para tratar de forma mas simple los datos
cmb1 = cb(row, col, la_z)
#print(cmb1)
cp1 = cp(cmb1, elarreglo)

# utilizamos los datos ingresados para ubicar un limite en las tres posiciones x,y,z con los identificadores
row, col, la_z = lim(*id[num2])
cmb2 = cb(row, col, la_z)
#print(cmb2)

Realizamos la copia el reemplazo, imprimos el arreglo y por ultimo Imprimos el fin del programa.

In [0]:
copia2 = cp(cmb2, elarreglo)
# reeemplzamos 
replace(cp1, cmb2, elarreglo)
replace(copia2, cmb1, elarreglo)
# imprimimmos el resultado final
print(elarreglo)

print('--FINAL--')

[[[  0   1   2 297 298 299   6   7   8]
  [  9  10  11 306 307 308  15  16  17]
  [ 18  19  20 315 316 317  24  25  26]
  [ 27  28  29  30  31  32  33  34  35]
  [ 36  37  38  39  40  41  42  43  44]
  [ 45  46  47  48  49  50  51  52  53]
  [ 54  55  56  57  58  59  60  61  62]
  [ 63  64  65  66  67  68  69  70  71]
  [ 72  73  74  75  76  77  78  79  80]]

 [[ 81  82  83 378 379 380  87  88  89]
  [ 90  91  92 387 388 389  96  97  98]
  [ 99 100 101 396 397 398 105 106 107]
  [108 109 110 111 112 113 114 115 116]
  [117 118 119 120 121 122 123 124 125]
  [126 127 128 129 130 131 132 133 134]
  [135 136 137 138 139 140 141 142 143]
  [144 145 146 147 148 149 150 151 152]
  [153 154 155 156 157 158 159 160 161]]

 [[162 163 164 459 460 461 168 169 170]
  [171 172 173 468 469 470 177 178 179]
  [180 181 182 477 478 479 186 187 188]
  [189 190 191 192 193 194 195 196 197]
  [198 199 200 201 202 203 204 205 206]
  [207 208 209 210 211 212 213 214 215]
  [216 217 218 219 220 221 222 223 2