#NUMPY

#INTRODUCCIÓN A LOS ARREGLOS



---


###CREANDO ARREGLOS


---



Importando Numpy y asignándole un alias

In [0]:
import numpy as np

Una sola dimensión

In [0]:
# Arreglo de integers
ai = np.array([4,7,9])
print(ai)
print(type(ai[2]))

In [0]:
# Arreglo de floats
af = np.array([4,7.3,9.1])
print(af)
print(type(af[2]))
print(type(af[0]))

In [0]:
# Arreglo de strings
am = np.array([4,7.3,'hola'])
print(am)
print(type(am[0]))

In [0]:
# Definir el tipo de dato
a = np.array([33,40,5],dtype=complex)
print(a)
a = np.array([33,40,5],dtype=float)
print(a)
a = np.array([4.5,7.32,9.01],dtype = int)
print(a)


Varias dimensiones

In [0]:
# Dos dimensiones
m = np.array([[4,7,9],[3,5,8],[1,6,2]]) #[e1,e2,e3]
print(m)

[[4 7 9]
 [3 5 8]
 [1 6 2]]


In [0]:
# Tres dimensiones
m3 = np.array([[[3,6,9],[1,1,2],[1,2,2]],[[3,3,3],[5,5,8],[8,5,8]],[[6,6,2],[2,2,2],[1,1,1]]])
print(m3)



---

###CREANDO ARREGLOS E INGRESANDO DATOS AUTOMÁTICAMENTE


---



Zeros

In [0]:
c = np.zeros((5,5,3))
print(c)
c = np.zeros((5,5), dtype=int)
print(c)

Unos

In [0]:
d = np.ones((5,5))
print(d)

Vacio

In [0]:
g = np.empty((3,3))
print(g)
h = np.empty((2,2))
print(h)

Llenar con el mismo número

In [0]:
b = np.full((3,3),5)
print(b)

Llenar con números aleatorios

In [0]:
b = np.random.random((3,3))
print(b)

Matriz idéntica

In [0]:
m = np.eye(5,5)
print(m)
m = np.eye(5,3)
print(m)
m = np.eye(3,5)
print(m)

Rangos

In [0]:
n = np.arange(0,20,2)
print(n)
n = np.arange(0,5,0.3)
print(n)


Espacios lineales

In [0]:
n = np.linspace(0,4,10)
print(n)

In [0]:
import math
x = np.linspace( 0, 2*math.pi, 20 )
print(x)
f = np.sin(x)
print(f)



---
###Reformando y redimensionando


---




Reformar

In [0]:
n = np.arange(20)
print(n)
n = np.arange(20).reshape(5,4)
print(n)
n.reshape(10,2)

In [0]:
n = np.arange(24)
print(n)
n = np.arange(24).reshape(2,4,3)
print(n)

In [0]:
a = np.reshape(n,(12,2))
print(a)
a = n.reshape(12,2)
print(a)
print(n)

Redimensionar

In [0]:
print(a)
b = np.resize(a,(4))
print(b)

In [0]:
print(b)
c = np.resize(b,(2,3))
print(c)

[0 1 2 3]
[[0 1 2]
 [3 0 1]]




---

###ATRIBUTOS DE LOS ARREGLOS


---



In [0]:
n = np.arange(32).reshape(2,4,4)
print(n)
print('\nDimensiones:',n.ndim)
print('Forma:',n.shape)
print('Tamaño',n.size)
print('Tipo de dato:',n.dtype)
print('Tamaño (bytes) de un elemento:',n.itemsize)
print('Dirección en memoria:',n.data)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]]

Dimensiones: 3
Forma: (2, 4, 4)
Tamaño 32
Tipo de dato: int64
Tamaño (bytes) de un elemento: 8
Dirección en memoria: <memory at 0x7fa94b3777c8>




---

###MÉTODOS MATEMÁTICOS DE LOS ARREGLOS


---



In [0]:
n = np.array([4,7.3,6.8,2,5])
print(n)
print("Redondeo:",n.round())
print("Suma:",n.sum())
print("Producto:",n.prod())
print("Suma acumulativa:",n.cumsum())
print("Media artimética:",n.mean())
print("Máximo:",n.max())
print("Mínimo:",n.min())
print("Ind máximo:",n.argmax())
print("Ind mínimo:",n.argmin())
