#INDEXING - SLICING



---


###1 DIMENSIÓN


---



In [0]:
import numpy as np
v = np.arange(10)
print(v)

[0 1 2 3 4 5 6 7 8 9]


Indexing 1D

In [0]:
print(v)
print(v[3])
print(v[-2])

Slincing 1D

In [0]:
print(v)
print(v[1:7:2])
print(v[-2:10])
print(v[-3:3:-1])
print(v[:])



---
###2 DIMENSIONES


---




In [0]:
m = np.arange(20).reshape(5,4)
print(m)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


Indexing 2D

In [0]:
#simple
print(m,'\n')
print(m[2,1]) # [[y],[x]]
print(m[2]) # ¿Qué pasa si falta una coordenada?

In [0]:
#múltiple
print(m,'\n')
n = m[[1,2,3],[0,3,1]] # [[las y´s],[las x´s]]
print(n)
n = m[[1,2,3]] # ¿Qué pasa si falta una coordenada?
print(n)

Slicing 2D

In [0]:
# 2D->2D
print(m,'\n')
print(m[1:3, 1:3])
print(m[:, 1:3])
print(m[1:3,:])

In [0]:
# 2D->1D
print(m,'\n')
print(m[1:2, 1:3])
print(m[1:2, 1:3].reshape(2))



---


###3 DIMENSIONES


---



In [0]:
s = np.arange(40).reshape(2,5,4)
print(s)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]
  [16 17 18 19]]

 [[20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]
  [36 37 38 39]]]


Indexing 3D

In [0]:
print(s,'\n')

#simple
print(s[1,3,1]) # [z,y,x]
print(s[1,3]) # ¿Qué pasa si falta una coordenada?
print(s[1]) # ¿Qué pasa si faltan dos coordenadas?

In [0]:
#múltiple
print(s,'\n')
n = s[[1,0],[0,3],[1,2]] # [[las z´s],[las y´s],[las x´s]]
print(n)
n = s[[1,0],[0,3]] # ¿Qué pasa si falta una coordenada?
print(n)
n = s[[1,0]] # ¿Qué pasa si faltan dos coordenadas?
print(n)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]
  [16 17 18 19]]

 [[20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]
  [36 37 38 39]]] 

[21 14]
[[20 21 22 23]
 [12 13 14 15]]
[[[20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]
  [36 37 38 39]]

 [[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]
  [16 17 18 19]]]


Slicing 3D

In [0]:
# 3D->3D
print(s,'\n')
print(s[0:2,0:3,0:3])
print(s[:,:,0:3])

In [0]:
# 3D->2D
print(s,'\n')
print(s[:,0:1,:])
print(s[0:1,0:3,0:3].reshape(3,3))

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]
  [16 17 18 19]]

 [[20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]
  [36 37 38 39]]] 

[[[ 0  1  2  3]]

 [[20 21 22 23]]]
[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]]


In [0]:
# 3D->1D
print(s,'\n')
print(s[0:1,0:1,0:3])
print(s[0:1,0:1,0:3].reshape(3))

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]
  [16 17 18 19]]

 [[20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]
  [36 37 38 39]]] 

[[[0 1 2]]]
[0 1 2]
